# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ShuffleMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ShuffleMobile
  pod 'Firebase/Core'
  pod 'GoogleTagManager', '~> 6.0'

  target 'ShuffleMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ShuffleMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
